Added support for Python 3.7
zopefoundation/MultiMapping pull request #5
Opened 2018-10-03 09:59 UTC by vernans

2018-10-03 11:11 UTC, icemac approved these changes
LGTM.

2018-10-03 11:27 UTC, icemac requested changes
Python 3.7 tests are not run.

2018-10-03 13:07 UTC, vernans commented
@icemac also this.

2018-10-04 07:09 UTC, icemac approved these changes

2018-10-04 09:08 UTC, merged